export const EVENT_CATALOG_STATUSES = Object.freeze([
  "complete",
  "intentional_absence",
  "known_gap",
  "legacy_compatibility",
  "owner_decision_required",
  "unknown"
]);

export const EVENT_CATALOG_ROUTE_STATUSES = Object.freeze([
  "supported",
  "supported_fallback",
  "none",
  "unknown",
  "known_gap"
]);

export const EVENT_CATALOG_PUSH_POLICIES = Object.freeze([
  "eligible",
  "panel_only",
  "none",
  "unknown",
  "known_gap"
]);

export const EVENT_CATALOG_AI_RELEVANCE = Object.freeze([
  "none",
  "context_only",
  "audit_only",
  "confirmed_capability",
  "owner_decision_required",
  "unknown"
]);

export const EVENT_CATALOG_KNOWN_GAP_NOTIFICATION_KINDS = Object.freeze([
  "waiting"
]);

export const EVENT_CATALOG_SUPPORTED_ROUTES = Object.freeze([
  "ticket_detail",
  "tickets",
  "tasks",
  "ppe",
  "cleaning",
  "pm",
  "fleet",
  "team",
  "department_fallback_bi",
  "bi_fallback",
  "api_only",
  "install",
  "none"
]);

export const CANONICAL_EVENT_CATALOG = Object.freeze([
  {
    id: "ticket.create",
    domain: "tickets",
    operation: "ticket create",
    producer: "server/tickets/handler.js create path, UI ticket create flows, approved AI ticket create capability",
    authoritativeBoundary: "ticket API and server validation",
    historyIdentifiers: ["ticket log open/create entries"],
    auditIdentifiers: ["ticket:create", "ticketWriteAuditEvent"],
    notificationKinds: ["new"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "confirmed_capability",
    coverage: ["tests/ticketsApiHandler.test.js", "tests/aiAssistActionExecutionModel.test.js"],
    status: "complete",
    notes: "Create can be proposed by AI only through the existing ticket capability and normal server authority."
  },
  {
    id: "ticket.supplier_routing",
    domain: "transport",
    operation: "supplier routing",
    producer: "ticket responsibility normalization and fleet supplier lookup",
    authoritativeBoundary: "ticket API plus transport responsibility helpers",
    historyIdentifiers: ["ticket field/status history"],
    auditIdentifiers: ["ticket:update"],
    notificationKinds: ["new"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: ["tests/ticketLifecycleAuthority.test.js", "tests/ticketsApiHandler.test.js"],
    status: "legacy_compatibility",
    notes: "Routing is represented as ticket state rather than a standalone durable event."
  },
  {
    id: "ticket.supplier_technician_acceptance",
    domain: "transport",
    operation: "supplier technician acceptance",
    producer: "technician ticket action",
    authoritativeBoundary: "ticketLifecycleAuthority new -> in_progress guard",
    historyIdentifiers: ["status/assignment history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["upd"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "complete",
    notes: "Transport acceptance requires eligible supplier technician, supplier match, and assignee equal to actor."
  },
  {
    id: "ticket.no_equipment_waiting",
    domain: "transport",
    operation: "no-equipment waiting",
    producer: "eligible supplier technician action and waiting return helper",
    authoritativeBoundary: "ticketLifecycleAuthority new -> waiting guard",
    historyIdentifiers: ["waiting log/history", "waiting:no_equipment lifecycle stage"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["escalate", "waiting"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "known_gap",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js", "tests/waitingReturnReminderModel.test.js"],
    status: "known_gap",
    notes: "`waiting` is produced by the waiting-return helper but is not in the global notification or push kind catalogs."
  },
  {
    id: "ticket.work_start",
    domain: "tickets",
    operation: "work start",
    producer: "status transition into in_progress",
    authoritativeBoundary: "ticket lifecycle authority for status-changing writes",
    historyIdentifiers: ["status history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["upd"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "complete",
    notes: "Transport first work start is supplier technician acceptance; facility behavior follows existing facility lifecycle guards."
  },
  {
    id: "ticket.repair_complete",
    domain: "tickets",
    operation: "repair complete",
    producer: "assigned technician or authorized actor completion action",
    authoritativeBoundary: "ticket lifecycle authority completion guards",
    historyIdentifiers: ["completion/status history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["confirm", "ready"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "complete",
    notes: "Notification kind depends on current session and approval stage."
  },
  {
    id: "ticket.manager_approval",
    domain: "tickets",
    operation: "manager approval",
    producer: "manager approval action",
    authoritativeBoundary: "ticketLifecycleAuthority pending_user -> pending_admin guard",
    historyIdentifiers: ["approval/status history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["ready"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "complete",
    notes: "Transport manager ownership is server-checked; generic role display is not server authority."
  },
  {
    id: "ticket.rework",
    domain: "tickets",
    operation: "rework",
    producer: "manager return action",
    authoritativeBoundary: "ticketLifecycleAuthority technical return guards",
    historyIdentifiers: ["rework/return history", "log text containing return wording"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: ["back"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "legacy_compatibility",
    notes: "Some technician back notifications are still derived from history text."
  },
  {
    id: "ticket.admin_close",
    domain: "tickets",
    operation: "admin close",
    producer: "admin final close action",
    authoritativeBoundary: "ticket lifecycle authority close guard",
    historyIdentifiers: ["closure history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: [],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "intentional_absence",
    notes: "No dedicated close notification is currently modeled."
  },
  {
    id: "ticket.cancel",
    domain: "tickets",
    operation: "cancel",
    producer: "authorized cancellation action",
    authoritativeBoundary: "ticket lifecycle authority cancellation guards",
    historyIdentifiers: ["cancel/status history"],
    auditIdentifiers: ["ticket:status_change", "ticket:update"],
    notificationKinds: [],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/ticketLifecycleAuthority.test.js"],
    status: "intentional_absence",
    notes: "Technician active/waiting cancellation is blocked for transport."
  },
  {
    id: "ticket.priority_update",
    domain: "tickets",
    operation: "priority update",
    producer: "dedicated priority update operation",
    authoritativeBoundary: "ticket API priority operation",
    historyIdentifiers: ["priority history old/new value"],
    auditIdentifiers: ["ticket:priority_change", "ticket:update"],
    notificationKinds: [],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/ticketsApiHandler.test.js"],
    status: "owner_decision_required",
    notes: "Existing facility priority edit can affect dueAt/SLA target; do not change without a separate owner-approved goal."
  },
  {
    id: "ticket.downtime_update",
    domain: "tickets",
    operation: "downtime update",
    producer: "dedicated downtime update operation",
    authoritativeBoundary: "ticket API downtime operation",
    historyIdentifiers: ["downtime history old/new value"],
    auditIdentifiers: ["ticket:downtime_change", "ticket:update"],
    notificationKinds: ["escalate", "sla"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/ticketsApiHandler.test.js"],
    status: "complete",
    notes: "Downtime update can affect state-derived escalation visibility."
  },
  {
    id: "ticket.zone_location_update",
    domain: "tickets",
    operation: "zone/location update",
    producer: "ticket update operation",
    authoritativeBoundary: "ticket API generic update permission",
    historyIdentifiers: ["ticket update history when recorded"],
    auditIdentifiers: ["ticket:update"],
    notificationKinds: ["upd"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/ticketsApiHandler.test.js"],
    status: "unknown",
    notes: "No dedicated location event identifier was found."
  },
  {
    id: "ticket.transport_unit_update",
    domain: "transport",
    operation: "transport-unit update",
    producer: "ticket update operation",
    authoritativeBoundary: "ticket API generic update plus transport responsibility helpers",
    historyIdentifiers: ["ticket update history when recorded"],
    auditIdentifiers: ["ticket:update"],
    notificationKinds: ["upd"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/ticketsApiHandler.test.js"],
    status: "unknown",
    notes: "Unit/forklift changes may affect routing/SLA but no dedicated event identifier was found."
  },
  {
    id: "ticket.comment",
    domain: "tickets",
    operation: "ticket comment",
    producer: "ticket detail note/comment save path",
    authoritativeBoundary: "ticket API/update path where persisted",
    historyIdentifiers: ["ticket log entry"],
    auditIdentifiers: ["ticket:update"],
    notificationKinds: ["upd", "back"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/ticketDetailRenderSmoke.test.js"],
    status: "legacy_compatibility",
    notes: "Some returned/back notifications are inferred from log text."
  },
  {
    id: "work.task_create",
    domain: "work",
    operation: "task create",
    producer: "task/work UI save path",
    authoritativeBoundary: "existing work resource save path",
    historyIdentifiers: ["task record log/state"],
    auditIdentifiers: ["unknown"],
    notificationKinds: ["task"],
    routes: [{ name: "tasks", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/taskActionModel.test.js"],
    status: "unknown",
    notes: "Task reminder is state-derived; audit parity was not proven."
  },
  {
    id: "work.task_update",
    domain: "work",
    operation: "task update",
    producer: "task/work UI save path",
    authoritativeBoundary: "existing work resource save path",
    historyIdentifiers: ["task record log/state"],
    auditIdentifiers: ["unknown"],
    notificationKinds: ["task"],
    routes: [{ name: "tasks", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: ["tests/taskActionModel.test.js"],
    status: "unknown",
    notes: "Task update notification is date/state-derived."
  },
  {
    id: "work.meeting_create",
    domain: "work",
    operation: "meeting create",
    producer: "meeting UI save path",
    authoritativeBoundary: "existing work resource save path",
    historyIdentifiers: ["meeting record log/state"],
    auditIdentifiers: ["unknown"],
    notificationKinds: ["task"],
    routes: [{ name: "tasks", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "unknown",
    notes: "Meeting reminders reuse notification kind `task`."
  },
  {
    id: "work.meeting_update",
    domain: "work",
    operation: "meeting update",
    producer: "meeting UI save path",
    authoritativeBoundary: "existing work resource save path",
    historyIdentifiers: ["meeting record log/state"],
    auditIdentifiers: ["unknown"],
    notificationKinds: ["task"],
    routes: [{ name: "tasks", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "unknown",
    notes: "Meeting update audit parity was not proven."
  },
  {
    id: "fleet.pm_due_soon",
    domain: "fleet_pm",
    operation: "PM due soon",
    producer: "fleet maintenance policy and snapshot event calculation",
    authoritativeBoundary: "fleet/PM state",
    historyIdentifiers: ["fleet or PM source record"],
    auditIdentifiers: ["fleet:update when source changes"],
    notificationKinds: ["pm"],
    routes: [{ name: "pm", status: "supported" }, { name: "department_fallback_bi", status: "supported_fallback" }],
    pushPolicy: "panel_only",
    aiRelevance: "context_only",
    coverage: [],
    status: "intentional_absence",
    notes: "PM due is a state-derived reminder, not a durable event."
  },
  {
    id: "fleet.document_warning",
    domain: "fleet",
    operation: "fleet document warning",
    producer: "document status snapshot event calculation",
    authoritativeBoundary: "fleet document fields",
    historyIdentifiers: ["fleet document state"],
    auditIdentifiers: ["fleet:update when source changes"],
    notificationKinds: ["doc"],
    routes: [{ name: "fleet", status: "supported" }],
    pushPolicy: "panel_only",
    aiRelevance: "context_only",
    coverage: ["tests/notificationDocEventsWiring.test.js"],
    status: "intentional_absence",
    notes: "Document warnings are intentionally non-interrupting."
  },
  {
    id: "fleet.blocked_unit",
    domain: "fleet",
    operation: "blocked unit",
    producer: "unit block/ticket state snapshot calculation",
    authoritativeBoundary: "fleet/ticket state",
    historyIdentifiers: ["ticket/fleet state"],
    auditIdentifiers: ["ticket:update", "fleet:update"],
    notificationKinds: ["escalate"],
    routes: [{ name: "fleet", status: "supported" }, { name: "department_fallback_bi", status: "supported_fallback" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "complete",
    notes: "May route by ticket id or fleet context depending producer branch."
  },
  {
    id: "fleet.driver_request",
    domain: "fleet",
    operation: "driver request",
    producer: "fleet driver request state",
    authoritativeBoundary: "fleet handler/config state",
    historyIdentifiers: ["driver request state"],
    auditIdentifiers: ["fleet:update"],
    notificationKinds: ["driver"],
    routes: [{ name: "fleet", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "complete",
    notes: "Pending driver requests notify admins/managers from snapshot state."
  },
  {
    id: "fleet.driver_request_outcome",
    domain: "fleet",
    operation: "driver request outcome",
    producer: "config driverEvents",
    authoritativeBoundary: "fleet/config state",
    historyIdentifiers: ["driver event state"],
    auditIdentifiers: ["fleet:update"],
    notificationKinds: ["driver"],
    routes: [{ name: "department_fallback_bi", status: "supported_fallback" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "legacy_compatibility",
    notes: "Outcome notifications are derived from config driverEvents."
  },
  {
    id: "ppe.request_pending",
    domain: "ppe",
    operation: "request pending",
    producer: "PPE request state",
    authoritativeBoundary: "server/ppe/handler.js",
    historyIdentifiers: ["PPE request status"],
    auditIdentifiers: ["ppe:update", "ppe:create"],
    notificationKinds: ["ppe"],
    routes: [{ name: "ppe", status: "supported" }],
    pushPolicy: "panel_only",
    aiRelevance: "context_only",
    coverage: [],
    status: "complete",
    notes: "PPE pending notifications can be aggregate."
  },
  {
    id: "ppe.low_stock",
    domain: "ppe",
    operation: "low stock",
    producer: "PPE reorder model and item state",
    authoritativeBoundary: "PPE item stock state",
    historyIdentifiers: ["PPE item state"],
    auditIdentifiers: ["ppe:update"],
    notificationKinds: ["ppe"],
    routes: [{ name: "ppe", status: "supported" }],
    pushPolicy: "panel_only",
    aiRelevance: "context_only",
    coverage: [],
    status: "intentional_absence",
    notes: "Low stock is a state-derived reminder."
  },
  {
    id: "ppe.open_order",
    domain: "ppe",
    operation: "open order",
    producer: "PPE order state",
    authoritativeBoundary: "server/ppe/handler.js",
    historyIdentifiers: ["PPE order status"],
    auditIdentifiers: ["ppe:update", "ppe:create"],
    notificationKinds: ["ppe"],
    routes: [{ name: "ppe", status: "supported" }],
    pushPolicy: "panel_only",
    aiRelevance: "context_only",
    coverage: [],
    status: "complete",
    notes: "Open-order notification routes to PPE log/dashboard context."
  },
  {
    id: "cleaning.round_due",
    domain: "cleaning",
    operation: "round due",
    producer: "cleaning zone/window state",
    authoritativeBoundary: "cleaning round/zone state",
    historyIdentifiers: ["cleaning round state"],
    auditIdentifiers: ["cleaning:update when source changes"],
    notificationKinds: ["cleaning"],
    routes: [{ name: "cleaning", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "intentional_absence",
    notes: "Round due is a state-derived reminder."
  },
  {
    id: "cleaning.round_overdue",
    domain: "cleaning",
    operation: "round overdue",
    producer: "cleaning zone/window state",
    authoritativeBoundary: "cleaning round/zone state",
    historyIdentifiers: ["cleaning round state"],
    auditIdentifiers: ["cleaning:update when source changes"],
    notificationKinds: ["cleaning"],
    routes: [{ name: "cleaning", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "intentional_absence",
    notes: "Missed/overdue rounds are state-derived."
  },
  {
    id: "cleaning.complaint_created",
    domain: "cleaning",
    operation: "complaint created",
    producer: "server/public/complaintsHandler.js and cleaning complaint UI/API",
    authoritativeBoundary: "cleaning complaint handlers",
    historyIdentifiers: ["cleaning complaint record"],
    auditIdentifiers: ["cleaning:create for internal path", "unknown for public complaint path"],
    notificationKinds: ["cleaning"],
    routes: [{ name: "cleaning", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "known_gap",
    notes: "Public complaint audit parity was not proven."
  },
  {
    id: "cleaning.complaint_escalation",
    domain: "cleaning",
    operation: "complaint escalation",
    producer: "cleaning complaint status/escalation state",
    authoritativeBoundary: "cleaning complaint handlers",
    historyIdentifiers: ["cleaning complaint escalation state"],
    auditIdentifiers: ["cleaning:update"],
    notificationKinds: ["cleaning"],
    routes: [{ name: "cleaning", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "context_only",
    coverage: [],
    status: "complete",
    notes: "Escalated complaints notify admin/manager based on complaint state."
  },
  {
    id: "identity.first_install_completed",
    domain: "identity_installation",
    operation: "first install completed",
    producer: "server/install/handler.js",
    authoritativeBoundary: "/api/install",
    historyIdentifiers: ["install marker/lock state"],
    auditIdentifiers: ["bootstrap", "install"],
    notificationKinds: [],
    routes: [{ name: "install", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/installHandler.test.js"],
    status: "complete",
    notes: "Static install state only; no production POST should be used on a ready system."
  },
  {
    id: "identity.install_failure_cleanup",
    domain: "identity_installation",
    operation: "install failure cleanup",
    producer: "server/install/handler.js",
    authoritativeBoundary: "/api/install cleanup path",
    historyIdentifiers: ["install marker/lock recovery state"],
    auditIdentifiers: ["install_failure", "bootstrap"],
    notificationKinds: [],
    routes: [{ name: "install", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/installHandler.test.js"],
    status: "complete",
    notes: "Cleanup failure moves system to recovery-required rather than reopening first-run install."
  },
  {
    id: "identity.admin_recovery_bootstrap",
    domain: "identity_installation",
    operation: "admin recovery bootstrap",
    producer: "server/bootstrap/adminHandler.js",
    authoritativeBoundary: "/api/bootstrap/admin with env/token gates",
    historyIdentifiers: ["install marker/state"],
    auditIdentifiers: ["bootstrap"],
    notificationKinds: [],
    routes: [{ name: "api_only", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/bootstrapAdminHandler.test.js", "tests/installHandler.test.js"],
    status: "complete",
    notes: "Recovery bootstrap is disabled by default and requires explicit owner/env decision."
  },
  {
    id: "identity.last_admin_mutation_blocked",
    domain: "identity_authority",
    operation: "last-admin mutation blocked",
    producer: "user/admin authority handlers",
    authoritativeBoundary: "last active admin guard",
    historyIdentifiers: ["none on blocked mutation"],
    auditIdentifiers: ["user:update when handler records attempted/authorized changes"],
    notificationKinds: [],
    routes: [{ name: "api_only", status: "supported" }],
    pushPolicy: "none",
    aiRelevance: "none",
    coverage: ["tests/authorityVerificationModel.test.js"],
    status: "complete",
    notes: "One active admin is valid; removing the final active admin is blocked."
  },
  {
    id: "ai.assist",
    domain: "ai",
    operation: "AI assist",
    producer: "server/ai/assistHandler.js",
    authoritativeBoundary: "authenticated AI assist API",
    historyIdentifiers: ["none"],
    auditIdentifiers: ["ai_assist"],
    notificationKinds: [],
    routes: [{ name: "none", status: "none" }],
    pushPolicy: "none",
    aiRelevance: "audit_only",
    coverage: ["tests/aiAssistHandler.test.js"],
    status: "complete",
    notes: "AI assist is audit telemetry and context building, not a notification channel."
  },
  {
    id: "ai.confirmed_ticket_create",
    domain: "ai",
    operation: "AI confirmed ticket create",
    producer: "ticketCreateCapability",
    authoritativeBoundary: "normal ticket create capability and API validation",
    historyIdentifiers: ["ticket create history"],
    auditIdentifiers: ["ai_assist", "ticket:create"],
    notificationKinds: ["new"],
    routes: [{ name: "ticket_detail", status: "supported" }],
    pushPolicy: "eligible",
    aiRelevance: "confirmed_capability",
    coverage: ["tests/aiAssistActionExecutionModel.test.js"],
    status: "complete",
    notes: "AI ticket create remains within user permission and server validation."
  },
  {
    id: "ai.confirmed_ticket_update",
    domain: "ai",
    operation: "AI confirmed ticket update",
    producer: "none confirmed in current implementation",
    authoritativeBoundary: "owner decision required before any write capability",
    historyIdentifiers: ["none"],
    auditIdentifiers: ["none"],
    notificationKinds: [],
    routes: [{ name: "none", status: "none" }],
    pushPolicy: "none",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "owner_decision_required",
    notes: "No confirmed general AI ticket update capability was cataloged."
  },
  {
    id: "ai.confirmed_ticket_comment",
    domain: "ai",
    operation: "AI confirmed ticket comment",
    producer: "none confirmed in current implementation",
    authoritativeBoundary: "owner decision required before any write capability",
    historyIdentifiers: ["none"],
    auditIdentifiers: ["none"],
    notificationKinds: [],
    routes: [{ name: "none", status: "none" }],
    pushPolicy: "none",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "owner_decision_required",
    notes: "No confirmed AI ticket comment capability was cataloged."
  },
  {
    id: "ai.confirmed_task_create_update",
    domain: "ai",
    operation: "AI confirmed task create/update",
    producer: "none confirmed in current implementation",
    authoritativeBoundary: "owner decision required before any write capability",
    historyIdentifiers: ["none"],
    auditIdentifiers: ["none"],
    notificationKinds: [],
    routes: [{ name: "none", status: "none" }],
    pushPolicy: "none",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "owner_decision_required",
    notes: "AI can read task context; confirmed task write capability is not implemented."
  },
  {
    id: "ai.confirmed_meeting_create_update",
    domain: "ai",
    operation: "AI confirmed meeting create/update",
    producer: "none confirmed in current implementation",
    authoritativeBoundary: "owner decision required before any write capability",
    historyIdentifiers: ["none"],
    auditIdentifiers: ["none"],
    notificationKinds: [],
    routes: [{ name: "none", status: "none" }],
    pushPolicy: "none",
    aiRelevance: "owner_decision_required",
    coverage: [],
    status: "owner_decision_required",
    notes: "AI can read meeting context; confirmed meeting write capability is not implemented."
  }
]);

export const CANONICAL_EVENT_IDS = Object.freeze(CANONICAL_EVENT_CATALOG.map((entry) => entry.id));
