export const STAGING_SMOKE_REQUIRED_ENV = [
  "VITE_CMMS_APP_MODE",
  "VITE_CMMS_STORAGE_PROVIDER",
  "VITE_CMMS_STORAGE_API_URL",
  "VITE_SUPABASE_URL",
  "VITE_SUPABASE_ANON_KEY",
  "CMMS_KV_AUTH",
  "CMMS_KV_DRIVER",
  "CMMS_ALLOW_PRODUCTION_KV_BRIDGE",
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "CMMS_FILE_DRIVER",
  "CMMS_FILE_BUCKET",
  "CMMS_FILE_METADATA_DRIVER",
  "CMMS_AUDIT_DRIVER",
  "CMMS_PUBLIC_COMPLAINTS_ENABLED",
  "CMMS_PUBLIC_COMPLAINTS_DRIVER"
];

export const STAGING_SMOKE_OPTIONAL_ENV = [
  "CMMS_KV_SUPABASE_TABLE",
  "CMMS_FILE_METADATA_SUPABASE_TABLE",
  "CMMS_AUDIT_SUPABASE_TABLE",
  "CMMS_PUBLIC_COMPLAINT_RATE_LIMIT_MS",
  "VITE_CMMS_PUBLIC_COMPLAINT_API_URL"
];
