create table if not exists public.ai_conversations (
  id text primary key,
  owner_user_id text not null,
  title text not null default 'AI conversation',
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.ai_conversation_messages (
  id text primary key,
  conversation_id text not null references public.ai_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system-safe-event')),
  content text not null,
  request_id text,
  idempotency_key text,
  sequence bigint generated by default as identity,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists ai_conversations_owner_status_last_idx
  on public.ai_conversations(owner_user_id, status, last_message_at desc);

create index if not exists ai_conversation_messages_conversation_sequence_idx
  on public.ai_conversation_messages(conversation_id, sequence asc);

create unique index if not exists ai_conversation_messages_idempotency_idx
  on public.ai_conversation_messages(conversation_id, role, idempotency_key)
  where idempotency_key is not null and idempotency_key <> '';

alter table public.ai_conversations enable row level security;
alter table public.ai_conversation_messages enable row level security;

revoke all on table public.ai_conversations from public;
revoke all on table public.ai_conversations from anon;
revoke all on table public.ai_conversations from authenticated;
revoke all on table public.ai_conversation_messages from public;
revoke all on table public.ai_conversation_messages from anon;
revoke all on table public.ai_conversation_messages from authenticated;
revoke all on sequence public.ai_conversation_messages_sequence_seq from public;
revoke all on sequence public.ai_conversation_messages_sequence_seq from anon;
revoke all on sequence public.ai_conversation_messages_sequence_seq from authenticated;

grant select, insert, update, delete on table public.ai_conversations to service_role;
grant select, insert, update, delete on table public.ai_conversation_messages to service_role;
grant usage, select on sequence public.ai_conversation_messages_sequence_seq to service_role;
